services:
  server:
    build:
      context: .
    env_file:
      - .env
    container_name: lifi-server
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - db-data:/var/lib/mongoDB/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DBNAME}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - app
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
networks:
  app:
